blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    # ex: /blog/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /blog/1/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='blogpost'),
    # ex: /blog/1/addcomment
    url(r'^(?P<blog_id>\d+)/addcomment/$', views.add_comment, name='addcomment'),


)

main/urls.py
from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^music/', views.MusicView.as_view(), name='music'),
    url(r'^writing/', views.WritingView.as_view(), name='writing')
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(url='/main/', permanent=False)),
    url(r'^/$', RedirectView.as_view(url='/main/', permanent=False)),
    url(r'^main/', include('main.urls', namespace="main")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^.*$', RedirectView.as_view(url='/main/', permanent=False))
)

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class BlogPost(models.Model):
    text = models.TextField()
    post_title = models.CharField(max_length=500, blank=False, default='')
    pub_date = models.DateTimeField('date published', default=timezone.now())

    def __str__(self):
        return self.post_title

class BlogComment(models.Model):
    blogpost = models.ForeignKey(BlogPost)
    text = models.TextField()
    comment_title = models.CharField(max_length=500, blank=False, default='')
    comment_user = models.CharField(max_length=500, blank=False)
    pub_date = models.DateTimeField('date published', default=timezone.now())

    def __str__(self):
        return self.comment_title

main/models.py
from django.db import models

# Create your models here.
class WritingSample(models.Model):
    title = models.CharField(max_length=500, blank=False, default='')
    text = models.TextField()
    static_img_location = models.CharField(max_length=500, blank=True, default=None)
    archived = models.BooleanField(default=True)
    writing_type = models.CharField(max_length=100, blank=False, default='')

    def __str__(self):
        return self.title

class MusicSample(models.Model):
    title = models.CharField(max_length=500, blank=False, default='')
    text = models.CharField(max_length=2000, blank=False)
    embed_html = models.CharField(max_length=600, blank=False, default='')
    archived = models.BooleanField(default=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic

from blog.models import BlogPost, BlogComment

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_blog_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return BlogPost.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = BlogPost
    template_name = 'blog/blog_post.html'


def add_comment(request, blog_id):
    p = get_object_or_404(BlogPost, pk=blog_id)
    try:
        comment_title = request.POST['comment_title']
        comment_text = request.POST['comment_text']
        comment_user = request.POST['comment_user']
        if not comment_text:
            return render(request, 'blog/blog_post.html', {
                'blog_id': p.id,
                'error_message': "You didn't enter a comment title.",
            })
        if not comment_title:
            return render(request, 'blog/blog_post.html', {
                'blog_id': p.id,
                'error_message': "You didn't enter a comment title.",
            })
        if not comment_user:
            return render(request, 'blog/blog_post.html', {
                'blog_id': p.id,
                'error_message': "You didn't enter a username.",
            })
    except KeyError:
        return Http404("Something went wrong")
    newcomment = BlogComment()
    newcomment.blogpost = p
    newcomment.text = comment_text
    newcomment.comment_title = comment_title
    newcomment.comment_user = comment_user
    newcomment.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('blog:blogpost', args=(p.id,)))

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic

from main.models import WritingSample, MusicSample

def index(request):
    template = loader.get_template('main/index.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))

def contact(request):
    template = loader.get_template('main/contact.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))

def music(request):
    template = loader.get_template('main/music.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))

class MusicView(generic.ListView):
    template_name = "main/music.html"
    context_object_name = 'music_samples'

    def get_queryset(self):
        return MusicSample.objects.all().filter(archived=False)


class WritingView(generic.ListView):
    template_name = 'main/writing.html'
    context_object_name = 'writing_samples'

    def get_queryset(self):
        return WritingSample.objects.all().filter(archived=False)

blog/templates/blog/blog_post.html
{% extends "main/base.html" %}

{% block title %}{{ blogpost.post_title|title }}{% endblock %}
{% block header %}
<div id="blog_post_header">
<i id="pub_date">{{ blogpost.pub_date }}</i>
<div id="blog_title">{{ blogpost.post_title|title }}</div>
</div>
{% endblock %}

{% block content %}
<div>{{ blogpost.text}}</div><br><br>

<div id="comment_form">
<h3>Add Comment</h3>
<form action="{% url 'blog:addcomment' blogpost.id %}" method="post">
    {% csrf_token %}
    <div><label for="comment_user">Name</label><input type="text" name="comment_user" id="comment_user"/><br /></div>
    <div><label for="comment_title">Comment Title</label><input type="text" name="comment_title" id="comment_title"/><br /></div>
    <div><label for="comment_text">Comment Text</label><textarea name="comment_text" id="comment_text"></textarea></div>
<input type="submit" value="Submit" />
</form>
</div>
<div id="comments">
<h3>Previous Comments</h3>
{% for comment in blogpost.blogcomment_set.all %}
    <div>
        <h4>{{ comment.comment_title|title}}</h4>
        <p>{{ comment.text }}</p>
        <i>{{ comment.comment_user }} - {{ comment.pub_date }}</i>
    </div>
    <hr>
{% endfor %}
</div>
<br>
{% endblock %}

blog/templates/blog/index.html
{% extends "main/index.html" %}

{% block title %}Blog{% endblock %}
{% block header %}<h1>Blog</h1><hr>{% endblock %}

{% block content %}
{% if latest_blog_list %}
    {% for blog in latest_blog_list %}
        <div id="blog_post_snippet">
            <i id="pub_date">{{ blog.pub_date }}</i>
            <a href="{% url 'blog:blogpost' blog.id %}"><h3 id="blog_title">{{ blog.post_title|title }}</h3></a>
            <div id="blog_text"><p>{{ blog.text }}</div>
        </div>
    {% endfor %}
{% else %}
    <p>No blog posts are available.</p>
{% endif %}
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/type.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/bergamo.css' %}" />
    <script src="{% static 'main/js/jquery.embedly.min.js' %}"></script>

    <title>{% block title %}Basic Title{% endblock %}</title>
</head>

<body>
    <div>
        {% block sidebar %}
        <div id="menu_bar">
            <br>
            <a class="oraclelink" href="{% url 'main:writing' %}">Writing</a>
            <a class="oraclelink" href="{% url 'main:music' %}">Music</a>
            <a href="{% url 'main:index' %}"><img src="{% static 'main/images/catfish.png' %}" alt="Catfish" height="90" width="130"></a>
            <a class="oraclelink" href="{% url 'blog:index' %}">Blog</a>
            <a class="oraclelink" href="{% url 'main:contact' %}">Contact</a>
        </div>
        {% endblock %}
    </div>
    <h1>{% block header %}Basic Header{% endblock %}</h1>
    <hr>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

main/templates/main/contact.html
{% extends "main/index.html" %}
{% load staticfiles %}

{% block title %}Contact Information{% endblock %}
{% block header %}<h1>Contact Information</h1><hr>{% endblock %}
{% block content %}
<div>
    Andy Horng
    <br>    
    <img src="{% static 'main/images/email.png' %}" alt="Email" height="29" width="180">
    <br><br>
    San Francisco, California
    <br>
</div>
{% endblock %}

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/type.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/bergamo.css' %}" />
    <script src="{% static 'main/js/jquery.embedly.min.js' %}"></script>

    <title>{% block title %}Catfishy{% endblock %}</title>
</head>

<body>
<br>
<div>
    <img src="{% static 'main/images/catfish.png' %}" alt="Catfish" height="200" width="333">
</div>
    <br>
    <div>
        <a class="oraclelink" href="{% url 'main:writing' %}">Writing</a>
        <a class="oraclelink" href="{% url 'main:music' %}">Music</a>
        <a class="oraclelink" href="{% url 'blog:index' %}">Blog</a>
        <a class="oraclelink" href="{% url 'main:contact' %}">Contact Info</a>
    </div>
    <div>{% block header %}{% endblock %}</div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

main/templates/main/music.html
{% extends "main/index.html" %}

{% block title %}Music{% endblock %}
{% block header %}<h1>Music Streams</h1><hr>{% endblock %}

{% block content %}
{% if music_samples %}
    {% for sample in music_samples %}
        <div id="music_sample">
            <h3>{{ sample.title|title }}</h3>
            <div>{{ sample.text|truncatechars:1000|linebreaks }}</div>
            <div>{{ sample.embed_html|safe }}</div>
        </div>
    {% endfor %}
{% else %}
    <p>No Music Streams</p>
{% endif %}
{% endblock %}

main/templates/main/writing.html
{% extends "main/index.html" %}

{% block title %}Writing{% endblock %}
{% block header %}<h1>Writing</h1><hr>{% endblock %}

{% block content %}
{% if writing_samples %}
    {% for sample in writing_samples %}
        <div id="writing_sample">
            <h3>{{ sample.title|title}}</h3>
            {% if sample.writing_type == 'poetry' %}
            <div id="writing_centered">{{ sample.text|truncatechars:1000|linebreaks }}</div>
            {% else %}
            <div id="writing_regular">{{ sample.text|truncatechars:1000|linebreaks }}</div>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    <p>No writing samples</p>
{% endif %}
{% endblock %}